project_id = "eascmxesmuadwlmooyik"

[functions.shopify-upload]
verify_jwt = false

[functions.reset-upload-status]
verify_jwt = false

[functions.upload-worker]
verify_jwt = false

[functions.job-watchdog]
verify_jwt = false

[functions.create-redirects]
verify_jwt = false

[functions.merge-variants]
verify_jwt = false

[functions.prepare-upload]
verify_jwt = false

[functions.fetch-metafields]
verify_jwt = false

[functions.inspect-url]
verify_jwt = false

[functions.match-redirects]
verify_jwt = false

[functions.parse-sitemap]
verify_jwt = false

[functions.fetch-shopify-sitemap]
verify_jwt = false

[functions.create-metafield-definition]
verify_jwt = false
