project_id = "eascmxesmuadwlmooyik"

[functions.shopify-upload]
verify_jwt = false

[functions.reset-upload-status]
verify_jwt = false

[functions.upload-worker]
verify_jwt = false

[functions.job-watchdog]
verify_jwt = false

[functions.create-redirects]
verify_jwt = false
